version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor:
      name: node/default
      tag: '14.19.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test -- -u
workflows:
  build-and-test:
    jobs:
      - test
